SELECT DEPARTMENT_NAME "학과 명", CATEGORY "계열" 
FROM TB_DEPARTMENT;

SELECT DEPARTMENT_NAME ||'의 정원은' || CAPACITY || ' 명 입니다.' "학과별 정원" 
FROM TB_DEPARTMENT;

SELECT DEPARTMENT_NO, DEPARTMENT_NAME  FROM TB_DEPARTMENT;

SELECT STUDENT_NAME
FROM  TB_STUDENT
WHERE DEPARTMENT_NO = '001' 
AND ABSENCE_YN = 'Y'
AND SUBSTR(STUDENT_SSN, 8, 1) = 2;

SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO LIKE 'A513%' 
AND (STUDENT_NO BETWEEN 'A513079' AND 'A513119')
ORDER BY 1 DESC;

SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT
ORDER BY 1 ASC;

SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE STUDENT_NO LIKE 'A2%' 
AND STUDENT_ADDRESS LIKE '전주시%'
AND ABSENCE_YN = 'N';

SELECT STUDENT_ADDRESS
FROM TB_STUDENT;

SELECT STUDENT_NO "학번", STUDENT_NAME "이름", TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY 3 ASC;

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;

SELECT PROFESSOR_NAME 교수이름,  
TRUNC(ABS(MONTHS_BETWEEN(SYSDATE, TO_DATE('19'||SUBSTR(PROFESSOR_SSN, 1, 6), 'YYYY-MM-DD'))) /12) 나이
FROM TB_PROFESSOR 
ORDER BY 2;

SELECT SUBSTR(PROFESSOR_NAME, 2) 이름
FROM TB_PROFESSOR;

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - 
EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 6),'RRMMDD')) > 19;

SELECT TO_CHAR(TO_DATE('2020-12-25'), 'DAY')
FROM DUAL;

SELECT TO_CHAR(TO_DATE('99/10/11'), 'YYYY/MM/DD') "첫 번째", TO_CHAR(TO_DATE('49/10/11'), 'YYYY/MM/DD') "두 번째",
TO_CHAR(TO_DATE('99/10/11'), 'RRRR/MM/DD') "세 번째", TO_CHAR(TO_DATE('49/10/11'), 'RRRR/MM/DD') "네 번째"
FROM DUAL;

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO NOT LIKE 'A%';

SELECT ROUND(AVG(POINT),1) 평점
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
WHERE STUDENT_NO = 'A517178';

SELECT * FROM TB_STUDENT ts ;
SELECT * FROM TB_GRADE tg ;

SELECT DEPARTMENT_NO 학과번호, COUNT(*) "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO; 

SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

SELECT * FROM TB_GRADE;
SELECT * FROM TB_STUDENT;

SELECT SUBSTR(TERM_NO, 1, 4) 년도, ROUND(AVG(POINT), 1) "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4)
ORDER BY 1;

SELECT DEPARTMENT_NO 학과코드명, COUNT(*) "휴학생 수"
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- NULL 처리부터 하면됨







