CREATE TABLE "CATEGORIES"(
 CATEGORY_ID NUMBER CONSTRAINT PK PRIMARY KEY,
 CATEGORY_NAME VARCHAR2(100) UNIQUE
);

COMMENT ON COLUMN CATEGORIES.CATEGORY_ID IS '카테고리';
COMMENT ON COLUMN CATEGORIES.CATEGORY_NAME IS '카테고리 이름';

INSERT INTO CATEGORIES VALUES(1, '스마트폰');
INSERT INTO CATEGORIES VALUES(2, 'TV');
INSERT INTO CATEGORIES VALUES(3, 'Gaming');

SELECT * FROM CATEGORIES;
------------------------------------------------------------------------------------------------

CREATE TABLE PRODUCTS(
 PRODUCT_ID NUMBER PRIMARY KEY,
 PRODUCT_NAME VARCHAR2(100) NOT NULL,
 CATEGORY NUMBER REFERENCES CATEGORIES,
 PRICE NUMBER DEFAULT 0,
 STOCK_QUANTITY NUMBER DEFAULT 0
);

COMMIT;

INSERT INTO PRODUCTS VALUES(101, 'Apple iPhone 12', 1, 1500000, 30);
INSERT INTO PRODUCTS VALUES(102, 'Samsung Galaxy S24', 1, 1800000, 50);
INSERT INTO PRODUCTS VALUES(201, 'LG OLED TV', 2, 3600000, 10);
INSERT INTO PRODUCTS VALUES(301, 'Sont PlayStation 5', 3, 700000, 15);

COMMENT ON COLUMN PRODUCTS.PRODUCT_ID IS '상품 코드';

SELECT * FROM PRODUCTS;

CREATE TABLE CUSTOMERS(
 CUSTOMER_ID NUMBER PRIMARY KEY,
 NAME VARCHAR2(20) NOT NULL,
 GENDER CHAR(3) CHECK (GENDER IN ('남', '여')),
 ADDRESS VARCHAR2(100),
 PHONE VARCHAR2(30)
);

INSERT INTO CUSTOMERS VALUES(1, '홍길동', '남', '서울시 성동구 왕십리', '010-1111-2222');
INSERT INTO CUSTOMERS VALUES(2, '유관순', '여', '서울시 종로구 안국동', '010-3333-1111');

CREATE TABLE ORDERS(
 ORDER_ID NUMBER PRIMARY KEY,
 ORDER_DATE DATE DEFAULT SYSDATE,
 STATUS CHAR(1) DEFAULT 'N' CHECK (STATUS IN ('Y', 'N')),
 CUSTOMER_ID NUMBER REFERENCES CUSTOMERS,
 ON DELETE CASCADE
);